language: node_js

os:
  - linux

node_js:
  - node
cache: npm

install:
  - npm ci
script:
  - checkout
  - npm test
  - npm run coveralls
branches:
  only:
  - master

deploy:
  provider: pages
  cleanup: true
  local_dir: build
  token: $GITHUB_TOKEN
on:
  branch: master
