--- 
branches: 
  only: 
    - master
cache: npm
deploy: 
  github-token: $GITHUB_TOKEN
  local_dir: build
  provider: pages
  skip-cleanup: true
install: 
  - "npm ci"
language: node_js
node_js: 
  - node
script: "-npm test -nmp run build"
sudo: false
true: 
  branch: master
