sudo: false

language: node_js

os:
  -linux

node_js:
  - node
cache: npm

install:
  - npm ci

script:
  - npm test
  - nmp run build
branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  token: $GITHUB_TOKEN
on:
  branch: master
