language: node_js

node_js:
  - node
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run build
branches:
  only:
  - master

deploy:
  provider: pages
  cleanup: true
  local_dir: build
  token: $GITHUB_TOKEN
on:
  branch: master
