{
  "on": {
    "branch": "master"
  },
  "language": "node_js",
  "os": [
    "linux"
  ],
  "sudo": false,
  "node_js": [
    "node"
  ],
  "cache": {
    "npm": true
  },
  "install": [
    "npm ci"
  ],
  "script": [
    "-npm test -nmp run build"
  ],
  "branches": {
    "only": [
      "master"
    ]
  },
  "deploy": [
    {
      "provider": "pages",
      "local_dir": "build",
      "skip_cleanup": true,
      "token": "$GITHUB_TOKEN"
    }
  ]
  }
