language: node_js

node_js:
    - node
cache: npm

install:
  - npm ci

script:
  - npm test
  -nmp run build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build
  github-token: $GITHUB_TOKEN
on:
  branch: master
